# Generated by Django 2.0.3 on 2019-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0005_auto_20190309_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='Body1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='Body2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='Body3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
