# Generated by Django 2.0.3 on 2019-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0006_auto_20190309_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project/media/'),
        ),
        migrations.AddField(
            model_name='repair',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project/media/'),
        ),
        migrations.AddField(
            model_name='repair',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project/media/'),
        ),
        migrations.AddField(
            model_name='repair',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project/media/'),
        ),
        migrations.AddField(
            model_name='repair',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project/media/'),
        ),
    ]
