# Generated by Django 2.0.3 on 2019-04-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0007_auto_20190309_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cold_weld',
        ),
        migrations.DeleteModel(
            name='facing',
        ),
        migrations.DeleteModel(
            name='Piping',
        ),
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='repair',
        ),
        migrations.DeleteModel(
            name='spray',
        ),
        migrations.DeleteModel(
            name='Steel',
        ),
        migrations.DeleteModel(
            name='Tanks',
        ),
        migrations.DeleteModel(
            name='Welding',
        ),
    ]
