# Generated by Django 2.0.3 on 2019-04-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0009_auto_20190430_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacture',
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img4',
            field=models.ImageField(height_field=400, upload_to='Project/media/', width_field=400),
        ),
    ]
