# Generated by Django 2.0.3 on 2019-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0010_auto_20190430_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img4',
            field=models.ImageField(upload_to='Project/media/'),
        ),
    ]
