# Generated by Django 2.0.3 on 2019-04-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0012_auto_20190501_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminume_welding_project_1',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_1',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_1',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_1',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_2',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_2',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_2',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='aluminume_welding_project_2',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='ammonia_spherical_tank_maintenance',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project1',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project1',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project1',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project1',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project10',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project10',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project10',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project10',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project11',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project11',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project11',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project11',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project12',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project12',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project12',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project12',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project13',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project13',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project13',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project13',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project14',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project14',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project14',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project14',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project15',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project15',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project15',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project15',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project16',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project16',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project16',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project16',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project17',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project17',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project17',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project17',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project18',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project18',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project18',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project18',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project19',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project19',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project19',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project19',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project2',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project2',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project2',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project2',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project20',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project20',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project20',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project20',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project3',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project3',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project3',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project3',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project4',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project4',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project4',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project4',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project5',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project5',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project5',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project5',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project6',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project6',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project6',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project6',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project7',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project7',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project7',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project7',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project8',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project8',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project8',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project8',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project9',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project9',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project9',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='cold_welding_project9',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='compressor_housing_ss304_repair',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='construction_and_repair',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_heat_exchanger',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_heat_exchanger',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_heat_exchanger',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_heat_exchanger',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_1',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_1',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_1',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_1',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_2',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_2',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_2',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='copper_welding_project_2',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismandteling_and_reconstruction',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_and_welding_repair_of_reformer_incoloy_800_tube',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_old_expansion_joint',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismanteling_the_dri_reactor_spod',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismantle_a_waste_heat_boiler',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismantle_a_waste_heat_boiler',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='dismantle_a_waste_heat_boiler',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='epcco_ndt_test',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='epcco_ndt_test',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='epcco_ndt_test',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='epcco_ndt_test',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fabrication_and_coating',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fabrication_and_coating',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fabrication_and_coating',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img13',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img14',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img15',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img16',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='heat_exchanger_repair',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heat_exchangers',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heat_exchangers',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heat_exchangers',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heat_exchangers',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heat_exchangers',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heavy_trucks_structure',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heavy_trucks_structure',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heavy_trucks_structure',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='maintenance_of_heavy_trucks_structure',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_maintenance',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_maintenance',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_maintenance',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_maintenance',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_and_welding_of_heads_of_heavy_trucks',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_of_hard_wear_core',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_of_hard_wear_core',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_of_hard_wear_core',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_of_hard_wear_core',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='manufacture_of_hard_wear_core',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='oil_tank_fire',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='oil_tank_fire',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='penetrant_test',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='penetrant_test',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction2',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction2',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction2',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction2',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='piping_construction2',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_damaged_hydrolic_pislon_of_loader',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_incolloy_800_header_of_reforme_at_amonia',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='repair_of_treated_and_cracked_loader_bucket',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='replacement_of_the_second_stage_of_nitricacid_lower_ss304l',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='replacement_of_the_second_stage_of_nitricacid_lower_ss304l',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='replacement_of_the_second_stage_of_nitricacid_lower_ss304l',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='replacement_of_the_second_stage_of_nitricacid_lower_ss304l',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='replacement_of_the_second_stage_of_nitricacid_lower_ss304l',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='retubing_heat_exchanger',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='retubing_heat_exchanger',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='retubing_heat_exchanger',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='retubing_heat_exchanger',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='selection_of_the_suitable_hard_facing_electrocle',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='selection_of_the_suitable_hard_facing_electrocle',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='selection_of_the_suitable_hard_facing_electrocle',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='tanks_fabrication',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='tanks_fabrication',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='tanks_fabrication',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='tanks_fabrication',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='titanium_tube_at_nitric_acid_plant',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='titanium_tube_at_nitric_acid_plant',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='titanium_tube_at_nitric_acid_plant',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='titanium_tube_at_nitric_acid_plant',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='titanium_tube_at_nitric_acid_plant',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='ultra_sonic',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='ultra_sonic',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='ultra_sonic',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='ultra_sonic',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img13',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img14',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img15',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img16',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img17',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img18',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img19',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img20',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img21',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img22',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img23',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img24',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_of_broken_and_cracked_parts_for_cast_iron_pump_housing2',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_of_heavy_truck_rims',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_of_heavy_truck_rims',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_of_heavy_truck_rims',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img13',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img14',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img15',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img16',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img17',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img18',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img19',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img20',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img5',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img6',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img7',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img8',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='welding_repair_ss304h_tube_cladded_innerly',
            name='img9',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
    ]
