# Generated by Django 2.0.3 on 2019-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0013_auto_20190501_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='img4',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fubrication_errection_of_steel_structure',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
