# Generated by Django 2.0.3 on 2019-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0015_auto_20190501_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
