# Generated by Django 2.0.3 on 2019-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0017_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img10',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AddField(
            model_name='events',
            name='img11',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AddField(
            model_name='events',
            name='img12',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
        migrations.AddField(
            model_name='events',
            name='img13',
            field=models.ImageField(blank=True, upload_to='Project'),
        ),
    ]
