# Generated by Django 2.0.3 on 2019-05-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0018_auto_20190531_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='eventi',
        ),
    ]
